baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'hugo-coder'

# Source: https://github.com/luizdepra/hugo-coder/blob/main/docs/configurations.md#complete-example
# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"
